test:
  image: "$CI_REGISTRY_IMAGE/buildenv:latest"
  stage: test
  script:
    - dotnet test

publish:
  image: "$CI_REGISTRY_IMAGE/buildenv:latest"
  stage: publish
  script:
    - curl "$BMBF_KEYSTORE_URL" --output BMBF.keystore
    - dotnet publish ./BMBF/BMBF.csproj -c Release
  artifacts:
    paths:
      - ./BMBF/bin/Release/net6.0-android/android-arm64/publish/*-Signed.apk


docker-buildenv:
  image: docker:latest
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/buildenv" -f buildenv.Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/buildenv"
  only:
    refs:
      - master
    changes:
      - buildenv.Dockerfile
