name: Build BMBF

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.101'
    - name: Install Android workload
      run: dotnet workload install android
    - name: Test
      run: dotnet test
    - name: Publish
      run: dotnet publish BMBF/BMBF.csproj -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: com.weareneutralaboutoculus.BMBF.apk
        path: ./BMBF/bin/Release/net6.0-android/android-arm64/publish/*.apk
